export const
    //APPLICATION ACTIONS
    APP_LOAD_STATE = 'APP_LOAD_STATE',
    APP_RESET_STATE = 'APP_RESET_STATE',
    //SYNTH ACTIONS
    SET_POSITIONS = 'SET_POSITIONS',
    SET_GRAPH_PAN = 'SET_GRAPH_PAN',
    SET_GRAPH_ZOOM = 'SET_GRAPH_ZOOM',
    ADD_NODE = 'ADD_NODE',
    REMOVE_NODE = 'REMOVE_NODE',
    REMOVE_NODES = 'REMOVE_NODES',
    LINK_NODES = 'LINK_NODES',
    UPDATE_NODE = 'UPDATE_NODE',
    SET_NODE_SELECTION = 'SET_NODE_SELECTION',
    SET_LINK_MODE = 'SET_LINK_MODE',
    TOGGLE_LINK_MODE = 'TOGGLE_LINK_MODE',
    OCTAVE_INCREASE = 'OCTAVE_INCREASE',
    OCTAVE_DECREASE = 'OCTAVE_DECREASE',
    SET_VIEW_PANEL = 'SET_VIEW_PANEL',
    SET_PIANO_VISIBILITY = 'SET_PIANO_VISIBILITY',
    SET_SPECTRUM_VISIBILITY = 'SET_SPECTRUM_VISIBILITY',
    UPDATE_PLAYING_VOICES = 'UPDATE_PLAYING_VOICES';

