export const
    SET_POSITIONS = 'SET_POSITIONS',
    ADD_AUDIO_NODE = 'ADD_AUDIO_NODE',
    REMOVE_NODE = 'REMOVE_NODE',
    REMOVE_NODES = 'REMOVE_NODES',
    SET_AUDIO_NODE_SELECTION = 'SET_AUDIO_NODE_SELECTION',
    SET_LINK_MODE = 'SET_LINK_MODE',
    TOGGLE_LINK_MODE = 'TOGGLE_LINK_MODE';

