export const
    INCREMENT_COUNTER = 'INCREMENT_COUNTER',
    DECREMENT_COUNTER = 'DECREMENT_COUNTER',

    ADD_AUDIO_NODE = 'ADD_AUDIO_NODE',
    SET_AUDIO_NODE_SELECTION = 'SET_AUDIO_NODE_SELECTION',
    SET_LINK_MODE = 'SET_LINK_MODE',
    TOGGLE_LINK_MODE = 'TOGGLE_LINK_MODE';

